import { IExperience } from "./ui/Experience/Experience.interface";

export const experiences: IExperience[] = [
  {
    start: "2019",
    end: "Present",
    title: "Senior Data Engineer",
    org: "Orange Business Services",
    orgLink: "#",
    location: "Montpellier - France",
    points: [
      "Oversaw a team of 5 developers in building a French NLP model (with OCR) for automatic detection of changes in EU regulations for a cosmetics manufacturer.",
      "Led the the development of a generic library for integrating Qlik suite with an existing Angular app for real-time custom visualization of financial data.",
      "Implemented data integration piplines to process semi-structured data from multiple sources using Hadoop/Talend for various clients.",
      "Designed and Implemented Salesforce applications that rely on Talend REST APIs to display and interact with NoSQL HBase data.",
      "Developed Qlik Sense and Tableau dashboards along with the underlying ETL data integration processes for various clients.",
    ],
    technologies: [
      "Typescript",
      "Python",
      "Java",
      "SQL",
      "NoSQL",
      "React",
      "Angular",
      "FastAPI",
      "Spring Boot",
      "Qlik",
      "Talend",
      "Tableau",
      "Informatica",
      "Salesforce",
      "Mulesoft",
      "AWS",
      "GCP",
      "Azure",
      "Kubernetes",
      "CI/CD",
      "Elasticsearch",
    ],
  },
  {
    start: "2018",
    end: "2019",
    title: "Research Engineer",
    org: "University of Montpellier - LIRMM",
    orgLink: "#",
    location: "Montpellier - France",
    points: [
      "Formalized mathematical models and built a platform for real-time collective decision making based on potentially conflicting shared knowledge.",
      "Implemented modular architecture across the entire stack while overseeing deployment, documentation, and deliverable reports.",
      "Implemented Spring REST API with real-time collaboration using websockets.",
      "Implemented Angular Front-end with graph visualization and interaction.",
      "Tutoring and Lecturing duties (+300h) for graduate students (Databases, Human-Computer Interaction, Web Development)",
    ],
    technologies: [
      "Typescript",
      "Python",
      "Tensofrlow",
      "Java",
      "Spring Boot",
      "FastAPI",
      "NoSQL",
      "Semantic Web",
      "Docker",
      "Maven",
      "Git",
      "AWS",
    ],
  },
  {
    start: "2015",
    end: "2018",
    title: "Ph.D. In Artificial Intelligence",
    org: "University of Montpellier - LIRMM",
    orgLink: "#",
    location: "Montpellier - France",
    points: [
      "Formalized a unifying model able to perfrom reasoning with inconsistent or incoherent knowledge within various domains such as Databases, Data Quality, Semantic Web, Argumentation, Non-monotonique Reasoning, and Human Reasoning.",
      "Implemented various modules for parsing and reasoning with conflicting data based on the proposed formalism.",
      "Applied and implemented our models on different use-cases in the private and public sector from Data Quality to Collective Decision making.",
    ],
    technologies: [
      "Javascript",
      "Python",
      "Tensofrlow",
      "Java",
      "Spring Boot",
      "NoSQL",
      "Ontologies",
      "Docker",
      "Maven",
      "Git",
    ],
  },
  {
    start: "2012",
    end: "2013",
    title: "Junior Fullstack Developer",
    org: "Open Management System",
    orgLink: "#",
    location: "Constantine - Algeria",
    points: [
      "Implemented a user polling website using Laravel/PHP.",
      "Implemented a scheduling tool with replicated database using Java/MySql for a language training school.",
      "Implemented an Android app for Workout session planning for a Boxing club.",
    ],
    technologies: [
      "Javascript",
      "PHP",
      "Java",
      "Laravel",
      "SQL",
      "Maven",
      "Git",
    ],
  },
];
